name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
    inputs:
      env:
        description: "Environment (qa, stage, demo, live)"
        required: false
      tests:
        description: "Tests to run (wrap in commas and separate tests with spaces)"
        required: false
        default: ""
      tags:
        description: "Tags to run (e.g., @critical)"
        required: false
        default: ""
      browser:
        description: "Browser (all/chrome/firefox/webkit)"
        required: true
        default: "chrome"
        type: choice
        options:
          - all
          - chrome
          - firefox
          - webkit

  workflow_call:
    inputs:
      env:
        required: true
        type: string
      browser:
        required: false
        type: string
        default: ""

permissions:
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Log the parameters used
      run: |
          echo "## Parameters" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: \`Not specified\`" >> $GITHUB_STEP_SUMMARY

    - name: Run Playwright tests on ${{ matrix.browser }}
      run: npx playwright test --project=${{ matrix.browser }} --reporter=list
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

